name: Automated Test

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@master
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk 

