name: Automated Test

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]
 

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@master
      - run: flutter pub get
      - run: flutter test

